### ISSUE TITLE
Definir objetos de tipo Matriz y Vector

### ISSUE THREAD

**Issue by luisjhefeerson** [sebaxtian/MathCalc#1]
Se deben definir dos clases Matriz y vector (Arreglos bidimensionales de dimensiones mxn).
Los atributos de matriz es su tamaño, mxn. Por lo que un vector podría definirse como un objeto de la clase matriz de tamaño mx1.
El punto es que definir estas dos clases nos permitirá crear objetos de ese tipo y guardarlos así como realizar operaciones sobre estos.

**Comment by sebaxtian** [comment]
Ok, voy a trabajar en lo que es la clase Matriz y la subclase Vector.
